apiVersion: v1
kind: Pod
metadata:
  name: webapp
spec:
  containers:
    - image: 10449/angular:latest
      name: webapp
      imagePullPolicy: Always
      resources: {}
      ports:
        - containerPort: 5200
